version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.10.0-alpine
    ports:
      - '8080:8000'
    volumes:
      - .:/code
      - static_volume:/code/static
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
