# Generated by Django 4.2.1 on 2023-05-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_seller_remove_product_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteringvalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(to='product.filteringvalue'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.filteringoption')),
            ],
        ),
        migrations.AddField(
            model_name='filteringvalue',
            name='values',
            field=models.ManyToManyField(to='product.choice'),
        ),
    ]
